### ISSUE TITLE
Searches beginning with S crash the game.

### ISSUE THREAD

**Issue by mikeskey** [ProsperCraft/towncraft#1] opened 2018-02-16 18:41 UTC
Trying to search for anything in JEI that begins with the letter S immediately crashes the game. Has happened multiple times on both my PC and my fiance's PC therefore it is not only an issue for me and is an issue with the pack.

**Comment by ProsperCraft** [comment] 2018-02-16 18:48
Please paste the crash report to gist.

**Comment by ProsperCraft** [comment] 2018-02-16 19:05
Unable to reproduce-
https://i.gyazo.com/6887b8630f09904b703194304a75b322.gif

**Comment by ProsperCraft** [comment] 2018-03-13 22:20
Is this still happening with the latest update?

**Comment by ProsperCraft** [comment] 2018-04-04 15:42
This was resolved with an Immersive Railroading update.

**Closed as completed by ProsperCraft** 2018-04-04 15:42 UTC
Labels: Needs Feedback
